import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import "@styles/globals.css";
import { cn } from "@lib/utils";

import Providers from "./providers";

const roboto = Nunito({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  style: ["normal", "italic"],
  variable: "--roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="pt">
      <body className={cn(" font-mono font-semibold ", roboto.variable)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export default RootLayout;
